{% set version = '0.4.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dtrackr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dtrackr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dtrackr/dtrackr_{{ version }}.tar.gz
  sha256: 7f3595ec1bcc0955baca7964dd4849f8703aa9f731c7e6f5352d238776643c2e

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-v8
    - r-base64enc
    - r-dplyr >=1.1.0
    - r-fs
    - r-glue
    - r-htmltools
    - r-magrittr
    - r-pdftools
    - r-png
    - r-purrr
    - r-rlang
    - r-rsvg
    - r-stringr
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-v8
    - r-base64enc
    - r-dplyr >=1.1.0
    - r-fs
    - r-glue
    - r-htmltools
    - r-magrittr
    - r-pdftools
    - r-png
    - r-purrr
    - r-rlang
    - r-rsvg
    - r-stringr
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('dtrackr')"           # [not win]
    - "\"%R%\" -e \"library('dtrackr')\""  # [win]

about:
  home: https://terminological.github.io/dtrackr/index.html, https://github.com/terminological/dtrackr
  license: MIT
  summary: Track and document 'dplyr' data pipelines. As you filter, mutate, and join your way
    through a data set, 'dtrackr' seamlessly keeps track of your data flow and makes
    publication ready documentation of a data pipeline simple.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: dtrackr
# Title: Track your Data Pipelines
# Version: 0.4.4
# Authors@R: person(given = "Robert", family = "Challen", role = c("aut", "cre"), email = "rob.challen@bristol.ac.uk", comment = c(ORCID = "0000-0002-5504-7768"))
# Description: Track and document 'dplyr' data pipelines. As you filter, mutate, and join your way through a data set, 'dtrackr' seamlessly keeps track of your data flow and makes publication ready documentation of a data pipeline simple.
# License: MIT + file LICENSE
# Language: en-GB
# Imports: dplyr (>= 1.1.0), glue, htmltools, magrittr, rlang, rsvg, stringr, tibble, tidyr, utils, V8, fs, purrr, base64enc, pdftools, png
# Suggests: here, knitr, rmarkdown, tidyselect, devtools, testthat (>= 2.1.0), rstudioapi, survival, ggplot2, covr
# VignetteBuilder: knitr
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# Depends: R (>= 2.10)
# URL: https://terminological.github.io/dtrackr/index.html, https://github.com/terminological/dtrackr
# BugReports: https://github.com/terminological/dtrackr/issues
# NeedsCompilation: no
# Packaged: 2023-09-04 11:52:00 UTC; vp22681
# Author: Robert Challen [aut, cre] (<https://orcid.org/0000-0002-5504-7768>)
# Maintainer: Robert Challen <rob.challen@bristol.ac.uk>
# Repository: CRAN
# Date/Publication: 2023-09-04 12:10:02 UTC
